require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MircopostsController do

  # This should return the minimal set of attributes required to create a valid
  # Mircopost. As you add validations to Mircopost, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "content" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MircopostsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mircoposts as @mircoposts" do
      mircopost = Mircopost.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mircoposts).should eq([mircopost])
    end
  end

  describe "GET show" do
    it "assigns the requested mircopost as @mircopost" do
      mircopost = Mircopost.create! valid_attributes
      get :show, {:id => mircopost.to_param}, valid_session
      assigns(:mircopost).should eq(mircopost)
    end
  end

  describe "GET new" do
    it "assigns a new mircopost as @mircopost" do
      get :new, {}, valid_session
      assigns(:mircopost).should be_a_new(Mircopost)
    end
  end

  describe "GET edit" do
    it "assigns the requested mircopost as @mircopost" do
      mircopost = Mircopost.create! valid_attributes
      get :edit, {:id => mircopost.to_param}, valid_session
      assigns(:mircopost).should eq(mircopost)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mircopost" do
        expect {
          post :create, {:mircopost => valid_attributes}, valid_session
        }.to change(Mircopost, :count).by(1)
      end

      it "assigns a newly created mircopost as @mircopost" do
        post :create, {:mircopost => valid_attributes}, valid_session
        assigns(:mircopost).should be_a(Mircopost)
        assigns(:mircopost).should be_persisted
      end

      it "redirects to the created mircopost" do
        post :create, {:mircopost => valid_attributes}, valid_session
        response.should redirect_to(Mircopost.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mircopost as @mircopost" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mircopost.any_instance.stub(:save).and_return(false)
        post :create, {:mircopost => { "content" => "invalid value" }}, valid_session
        assigns(:mircopost).should be_a_new(Mircopost)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mircopost.any_instance.stub(:save).and_return(false)
        post :create, {:mircopost => { "content" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mircopost" do
        mircopost = Mircopost.create! valid_attributes
        # Assuming there are no other mircoposts in the database, this
        # specifies that the Mircopost created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mircopost.any_instance.should_receive(:update).with({ "content" => "MyText" })
        put :update, {:id => mircopost.to_param, :mircopost => { "content" => "MyText" }}, valid_session
      end

      it "assigns the requested mircopost as @mircopost" do
        mircopost = Mircopost.create! valid_attributes
        put :update, {:id => mircopost.to_param, :mircopost => valid_attributes}, valid_session
        assigns(:mircopost).should eq(mircopost)
      end

      it "redirects to the mircopost" do
        mircopost = Mircopost.create! valid_attributes
        put :update, {:id => mircopost.to_param, :mircopost => valid_attributes}, valid_session
        response.should redirect_to(mircopost)
      end
    end

    describe "with invalid params" do
      it "assigns the mircopost as @mircopost" do
        mircopost = Mircopost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mircopost.any_instance.stub(:save).and_return(false)
        put :update, {:id => mircopost.to_param, :mircopost => { "content" => "invalid value" }}, valid_session
        assigns(:mircopost).should eq(mircopost)
      end

      it "re-renders the 'edit' template" do
        mircopost = Mircopost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mircopost.any_instance.stub(:save).and_return(false)
        put :update, {:id => mircopost.to_param, :mircopost => { "content" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mircopost" do
      mircopost = Mircopost.create! valid_attributes
      expect {
        delete :destroy, {:id => mircopost.to_param}, valid_session
      }.to change(Mircopost, :count).by(-1)
    end

    it "redirects to the mircoposts list" do
      mircopost = Mircopost.create! valid_attributes
      delete :destroy, {:id => mircopost.to_param}, valid_session
      response.should redirect_to(mircoposts_url)
    end
  end

end
